name: Daily Green Dot Bot ðŸŸ¢

on:
  schedule:
    # S'exÃ©cute Ã  00:00 UTC tous les jours
    - cron: '0 0 * * *'
  workflow_dispatch: # Permet de le lancer manuellement pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Update heartbeat file
        run: |
          mkdir -p data
          echo "Last pulse: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > data/heartbeat.txt

      - name: Select random commit message
        id: message
        run: |
          MESSAGE=$(shuf -n 1 .github/commit_messages.txt)
          echo "commit_msg=$MESSAGE" >> $GITHUB_OUTPUT

      - name: Commit and Push
        run: |
          git config --local user.email "tahirydev29@gmail.com"
          git config --local user.name "Tahiry"
          git add data/heartbeat.txt
          git commit -m "$(shuf -n 1 .github/commit_messages.txt)" || echo "No changes to commit"
          git push
